name: Gerar APK Beit Tefila Yeshua

on:
  workflow_dispatch:
  push:
    branches:
      - principal
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 
      - name: Extrair projeto Android
        run: |
          unzip -o beit-tefila-yeshua-project.zip -d projeto

            - name: Compilar APK
        run: |
          cd "$DIRETORIO"
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Beit-Tefila-Yeshua-APK
          path: "$DIRETORIO/app/build/outputs/apk/debug/app-debug.apk"
